apiVersion: v1
kind: Pod
metadata:
  name: lm-training
spec:
  containers:
  - name: mypod
    image: pytorch/pytorch
    resources:
      limits:
        memory: 10Gi
        cpu: 4
        nvidia.com/gpu: 1
      requests:
        memory: 8Gi
        cpu: 3
    volumeMounts:
    - mountPath: /mltrain
      name: mltrain
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
  volumes:
    - name: mltrain
      persistentVolumeClaim:
        claimName: data-vol
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-GTX-1080-Ti